Added support for windows in watch scripts

diff --git a/watchserver b/watchserver
--- a/watchserver
+++ b/watchserver
@@ -1,2 +1,6 @@
 #!/bin/bash
-nodemon -x "go run . || exit 1" --signal SIGTERM -e go
+case "$OSTYPE" in
+  darwin*|linux*) nodemon -x "go run . || exit 1" --signal SIGTERM -e go ;;
+  msys*|cygwin*) nodemon -x "go run . || exit 1" --signal SIGKILL -e go ;;
+  *)        echo "Cannot start script with unknown OSTYPE: $OSTYPE" ;;
+esac
